# Generated by Django 4.0.8 on 2022-12-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_id', models.PositiveIntegerField()),
                ('husstands_id', models.PositiveIntegerField()),
                ('fem_års_aldersgrupper', models.CharField(max_length=200)),
                ('ti_års_aldersgrupper', models.CharField(max_length=200)),
                ('navn', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='f', max_length=1)),
                ('alder', models.FloatField()),
                ('ægteskablig_status', models.CharField(choices=[('ugift', 'ugift'), ('gift', 'gift'), ('enke', 'enke'), ('ukendt', 'ukendt'), ('skilt', 'skilt')], default='ukendt', max_length=100)),
                ('sogn_by', models.CharField(max_length=200)),
                ('herred', models.CharField(max_length=200)),
                ('amt', models.CharField(max_length=200)),
                ('bosted', models.CharField(choices=[('land', 'land'), ('by', 'by'), ('københavn', 'københavn')], default='land', max_length=100)),
                ('bostedtype', models.CharField(max_length=200)),
                ('erhverv_original', models.CharField(max_length=200)),
                ('stilling_i_husstanden_standardiseret', models.CharField(max_length=200)),
                ('fødested_original', models.CharField(max_length=200)),
                ('fødesogn_by_standardiseret', models.CharField(max_length=200)),
                ('migrant_type', models.CharField(choices=[('migrant', 'migrant'), ('indfødt', 'indfødt'), ('ukendt', 'ukendt')], default='ukendt', max_length=100)),
            ],
        ),
    ]
