# Generated by Django 4.0.8 on 2022-12-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Person',
        ),
    ]
