# Generated by Django 4.0.8 on 2022-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_data_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='migrant_type',
            field=models.CharField(choices=[('migrant', 'migrant'), ('indfødt', 'indfødt'), ('ukendt', 'ukendt')], default='indfødt', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='ægteskablig_status',
            field=models.CharField(choices=[('ugift', 'ugift'), ('gift', 'gift'), ('enke', 'enke'), ('ukendt', 'ukendt'), ('skilt', 'skilt')], default='gift', max_length=100),
        ),
    ]
