# Generated by Django 4.0.8 on 2022-12-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_person_migrant_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='gender',
            new_name='køn',
        ),
    ]
