# Generated by Django 4.0.8 on 2022-12-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_gender_person_køn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ægteskablig_status',
            new_name='ægteskablig_stilling',
        ),
    ]
