# Generated by Django 4.0.8 on 2022-12-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rename_ægteskablig_status_person_ægteskablig_stilling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ægteskablig_stilling',
            new_name='ægteskabelig_stilling',
        ),
    ]
