# Generated by Django 4.0.8 on 2022-12-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_bosted_person_bostedstype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
