# Generated by Django 4.0.8 on 2023-01-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_person_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='år',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
