# Generated by Django 4.0.8 on 2023-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_person_år'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['ægteskabelig_stilling'], name='person_ægteska_1afe11_idx'),
        ),
    ]
