# Generated by Django 4.0.8 on 2023-01-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_person_person_ægteska_1afe11_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='person_ægteska_1afe11_idx',
        ),
    ]
