# Generated by Django 4.0.8 on 2023-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_person_person_ægteska_1afe11_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ægteskabelig_stilling',
            field=models.CharField(choices=[('ugift', 'ugift'), ('gift', 'gift'), ('enke', 'enke'), ('ukendt', 'ukendt'), ('skilt', 'skilt')], db_index=True, default='gift', max_length=100),
        ),
    ]
