# Generated by Django 4.0.8 on 2023-02-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_person_ægteskabelig_stilling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-id']},
        ),
    ]
