# Generated by Django 4.0.8 on 2023-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_person_fødesogn_by_standardiseret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person1801',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('år', models.PositiveIntegerField(default=None)),
                ('pa_id', models.CharField(max_length=100)),
                ('husstands_id', models.PositiveIntegerField()),
                ('fem_års_aldersgrupper', models.CharField(max_length=200)),
                ('ti_års_aldersgrupper', models.CharField(max_length=200)),
                ('navn', models.CharField(max_length=200)),
                ('køn', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='f', max_length=1)),
                ('alder', models.PositiveIntegerField()),
                ('ægteskabelig_stilling', models.CharField(choices=[('ugift', 'ugift'), ('gift', 'gift'), ('enke', 'enke'), ('ukendt', 'ukendt'), ('skilt', 'skilt')], db_index=True, default='gift', max_length=100)),
                ('sogn_by', models.CharField(max_length=200)),
                ('herred', models.CharField(max_length=200)),
                ('amt', models.CharField(max_length=200)),
                ('bostedstype', models.CharField(choices=[('land', 'land'), ('by', 'by'), ('københavn', 'københavn')], default='land', max_length=100)),
                ('erhverv_original', models.CharField(max_length=200)),
                ('stilling_i_husstanden_standardiseret', models.CharField(max_length=200)),
                ('stilling_i_husstanden_original', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'person1801',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Person1850',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('år', models.PositiveIntegerField(default=None)),
                ('pa_id', models.CharField(max_length=100)),
                ('husstands_id', models.PositiveIntegerField()),
                ('fem_års_aldersgrupper', models.CharField(max_length=200)),
                ('ti_års_aldersgrupper', models.CharField(max_length=200)),
                ('navn', models.CharField(max_length=200)),
                ('køn', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='f', max_length=1)),
                ('alder', models.PositiveIntegerField()),
                ('ægteskabelig_stilling', models.CharField(choices=[('ugift', 'ugift'), ('gift', 'gift'), ('enke', 'enke'), ('ukendt', 'ukendt'), ('skilt', 'skilt')], db_index=True, default='gift', max_length=100)),
                ('sogn_by', models.CharField(max_length=200)),
                ('herred', models.CharField(max_length=200)),
                ('amt', models.CharField(max_length=200)),
                ('bostedstype', models.CharField(choices=[('land', 'land'), ('by', 'by'), ('københavn', 'københavn')], default='land', max_length=100)),
                ('erhverv_original', models.CharField(max_length=200)),
                ('stilling_i_husstanden_standardiseret', models.CharField(max_length=200)),
                ('fødested_original', models.CharField(max_length=200)),
                ('fødesogn_by_standardiseret', models.CharField(max_length=200)),
                ('migrant_type', models.CharField(choices=[('migrant', 'migrant'), ('indfødt', 'indfødt'), ('ukendt', 'ukendt')], default='indfødt', max_length=100)),
            ],
            options={
                'db_table': 'person1850',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Person1901',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('år', models.PositiveIntegerField(default=None)),
                ('pa_id', models.CharField(max_length=100)),
                ('husstands_id', models.PositiveIntegerField()),
                ('fem_års_aldersgrupper', models.CharField(max_length=200)),
                ('ti_års_aldersgrupper', models.CharField(max_length=200)),
                ('navn', models.CharField(max_length=200)),
                ('køn', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='f', max_length=1)),
                ('alder', models.PositiveIntegerField()),
                ('ægteskabelig_stilling', models.CharField(choices=[('ugift', 'ugift'), ('gift', 'gift'), ('enke', 'enke'), ('ukendt', 'ukendt'), ('skilt', 'skilt')], db_index=True, default='gift', max_length=100)),
                ('sogn_by', models.CharField(max_length=200)),
                ('herred', models.CharField(max_length=200)),
                ('amt', models.CharField(max_length=200)),
                ('bostedstype', models.CharField(choices=[('land', 'land'), ('by', 'by'), ('københavn', 'københavn')], default='land', max_length=100)),
                ('erhverv_original', models.CharField(max_length=200)),
                ('stilling_i_husstanden_standardiseret', models.CharField(max_length=200)),
                ('stilling_i_husstanden_original', models.CharField(max_length=200)),
                ('fødested_original', models.CharField(max_length=200)),
                ('fødesogn_by_standardiseret', models.CharField(max_length=200)),
                ('migrant_type', models.CharField(choices=[('migrant', 'migrant'), ('indfødt', 'indfødt'), ('ukendt', 'ukendt')], default='indfødt', max_length=100)),
            ],
            options={
                'db_table': 'person1901',
                'ordering': ['-id'],
            },
        ),
    ]
