# Generated by Django 4.0.8 on 2023-06-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_person1801_person1850_person1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person1801',
            name='år',
        ),
        migrations.RemoveField(
            model_name='person1850',
            name='år',
        ),
        migrations.RemoveField(
            model_name='person1901',
            name='år',
        ),
    ]
