# Generated by Django 4.0.8 on 2023-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_remove_person1801_år_remove_person1850_år_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person1801',
            name='husstands_størrelse',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person1850',
            name='husstands_størrelse',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person1901',
            name='husstands_størrelse',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='alder',
            field=models.IntegerField(),
        ),
    ]
