# Generated by Django 4.0.8 on 2023-07-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_person1801_husstands_størrelse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person1801',
            name='alder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person1850',
            name='alder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person1901',
            name='alder',
            field=models.IntegerField(),
        ),
    ]
